"""Reproducible Phase 12 Track B showcase execution and release profiling."""

from __future__ import annotations

import math
import os
import tempfile
from collections.abc import Iterable
from importlib.resources import files
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from oasis.evaluation import (
    BenchmarkManifest,
    BenchmarkRunRecord,
    ComparisonKind,
    load_manifest,
    read_run_records,
    run_benchmark,
)
from oasis.schemas import ArtifactRef, PrivacyClassification

SHOWCASE_SCHEMA_VERSION: Literal["1.0.0"] = "1.0.0"
MAX_COMPACT_CONTEXT_BYTES = 16_384


class ShowcaseDataset(BaseModel):
    """Frozen dataset identity, rights, refresh path, and explicit scope."""

    model_config = ConfigDict(frozen=True)

    schema_version: Literal["1.0.0"] = SHOWCASE_SCHEMA_VERSION
    id: str = "oasis-track-b-synthetic-snapshot-v1"
    title: str = "OASIS Track B synthetic public-health snapshot"
    source_uri: str = "oasis://evaluation/track-b-showcase-v1"
    source_version: str = "1.0.0"
    license: str = "CC0-1.0"
    attribution: str = (
        "Generated by the OASIS 1.0.0 seeded synthetic-instance generator; no patient or "
        "person-level records are included."
    )
    privacy: PrivacyClassification = PrivacyClassification.PUBLIC
    generator_version: str = "1.0.0"
    split: str = "held_out"
    refresh_command: str = "uv run oasis evidence live-smoke --confirm-live-network ..."
    included_problem_types: tuple[str, ...] = (
        "max_weighted_coverage",
        "weighted_p_median",
        "quantile_access",
        "capacitated_allocation",
        "equity_coverage",
        "resilient_coverage",
        "mobile_service_route",
    )
    deferred_scenarios: dict[str, str] = {
        "monitor_placement": (
            "Deferred: no validated exposure, detection, or prediction-variance impact model is "
            "available, so a generic p-center proxy is not presented as a health-impact result."
        )
    }


class ToolLatencyProfile(BaseModel):
    """Observed offline latency compared with the admission estimate in the tool contract."""

    model_config = ConfigDict(frozen=True)

    observations: int = Field(ge=1)
    measured_p50_ms: int = Field(ge=0)
    measured_p95_ms: int = Field(ge=0)
    declared_p50_ms: int = Field(ge=0)
    declared_p95_ms: int = Field(ge=0)
    within_declared_p95: bool


class ReleaseProfile(BaseModel):
    """Bounded resource measurements collected from normal controller traces."""

    model_config = ConfigDict(frozen=True)

    run_count: int = Field(ge=1)
    model_action_count: int = Field(ge=0)
    max_model_action_input_tokens: int = Field(ge=0)
    max_model_action_generated_tokens: int = Field(ge=0)
    max_compact_context_bytes: int = Field(ge=0)
    compact_context_limit_bytes: int = MAX_COMPACT_CONTEXT_BYTES
    compact_context_within_limit: bool
    max_artifact_count_per_run: int = Field(ge=0)
    max_artifact_bytes_per_run: int = Field(ge=0)
    max_single_artifact_bytes: int = Field(ge=0)
    max_deadline_overshoot_ms: int = Field(ge=0)
    tool_latency: dict[str, ToolLatencyProfile]


class MetadataAudit(BaseModel):
    """Release audit of immutable evidence metadata and trace-safe serialization."""

    model_config = ConfigDict(frozen=True)

    artifact_count: int = Field(ge=1)
    licenses: tuple[str, ...]
    source_providers: tuple[str, ...]
    all_public: bool
    all_sources_attributed: bool
    all_licenses_declared: bool
    no_sensitive_metadata_keys: bool
    reproducibility_complete: bool


class ShowcaseInstanceReport(BaseModel):
    """One domain-readable result selected only from independent evaluator records."""

    model_config = ConfigDict(frozen=True)

    id: str
    problem_type: str
    comparison: ComparisonKind
    raw_objective: dict[str, float]
    overall_metrics: dict[str, float]
    group_metrics: dict[str, dict[str, float]]
    scenario_metrics: dict[str, dict[str, float]]
    baseline_gain: float
    comparator_history: tuple[tuple[float, ...], ...]
    problem_hash: str
    evidence_hash: str
    policy_hash: str


class ShowcaseBenchmarkSummary(BaseModel):
    """Concise benchmark identity; detailed aggregates remain in ``summary.json``."""

    model_config = ConfigDict(frozen=True)

    benchmark_id: str
    manifest_hash: str
    run_count: int = Field(ge=1)
    aggregate_group_count: int = Field(ge=1)
    paired_delta_count: int = Field(ge=0)


class ShowcaseReport(BaseModel):
    """Complete machine-readable release result written by ``oasis demo``."""

    model_config = ConfigDict(frozen=True)

    schema_version: Literal["1.0.0"] = SHOWCASE_SCHEMA_VERSION
    dataset: ShowcaseDataset
    default_budget: dict[str, int | None]
    benchmark_summary: ShowcaseBenchmarkSummary
    instances: tuple[ShowcaseInstanceReport, ...]
    profile: ReleaseProfile
    metadata_audit: MetadataAudit
    hardware_validation: dict[str, str]
    limitations: tuple[str, ...]


def showcase_manifest_path() -> Path:
    """Return the package-owned manifest path used by the public demo command."""

    return Path(str(files("oasis.evaluation").joinpath("manifests", "showcase.json")))


def load_showcase_manifest() -> BenchmarkManifest:
    """Load the immutable default manifest through the normal public validator."""

    return load_manifest(showcase_manifest_path())


def _resolve_output_root(output_root: str | Path) -> Path:
    return Path(output_root).resolve()


def _percentile(values: Iterable[int], quantile: float) -> int:
    ordered = sorted(values)
    if not ordered:
        return 0
    index = max(0, math.ceil(quantile * len(ordered)) - 1)
    return ordered[index]


def _release_profile(records: tuple[BenchmarkRunRecord, ...]) -> ReleaseProfile:
    input_tokens = tuple(value for record in records for value in record.model_action_input_tokens)
    generated_tokens = tuple(
        value for record in records for value in record.model_action_generated_tokens
    )
    compact_bytes = tuple(value for record in records for value in record.compact_context_bytes)
    observations: dict[str, list[int]] = {}
    declared_p50: dict[str, int] = {}
    declared: dict[str, int] = {}
    for record in records:
        for name, values in record.tool_latency_observations_ms.items():
            observations.setdefault(name, []).extend(values)
        for name, value in record.tool_p50_estimates_ms.items():
            declared_p50[name] = value
        for name, value in record.tool_p95_estimates_ms.items():
            declared[name] = value
    tool_latency = {
        name: ToolLatencyProfile(
            observations=len(values),
            measured_p50_ms=_percentile(values, 0.50),
            measured_p95_ms=_percentile(values, 0.95),
            declared_p50_ms=declared_p50[name],
            declared_p95_ms=declared[name],
            within_declared_p95=_percentile(values, 0.95) <= declared[name],
        )
        for name, values in sorted(observations.items())
        if name in declared and name in declared_p50 and values
    }
    maximum_context = max(compact_bytes, default=0)
    return ReleaseProfile(
        run_count=len(records),
        model_action_count=len(input_tokens),
        max_model_action_input_tokens=max(input_tokens, default=0),
        max_model_action_generated_tokens=max(generated_tokens, default=0),
        max_compact_context_bytes=maximum_context,
        compact_context_within_limit=maximum_context <= MAX_COMPACT_CONTEXT_BYTES,
        max_artifact_count_per_run=max(record.artifact_count for record in records),
        max_artifact_bytes_per_run=max(record.artifact_bytes for record in records),
        max_single_artifact_bytes=max(record.largest_artifact_bytes for record in records),
        max_deadline_overshoot_ms=max(record.deadline_overshoot_ms for record in records),
        tool_latency=tool_latency,
    )


_SENSITIVE_FRAGMENTS = ("authorization", "api_key", "password", "secret", "token", "cookie")


def _has_sensitive_key(value: object) -> bool:
    if isinstance(value, dict):
        return any(
            any(fragment in str(key).lower() for fragment in _SENSITIVE_FRAGMENTS)
            or _has_sensitive_key(nested)
            for key, nested in value.items()
        )
    if isinstance(value, list):
        return any(_has_sensitive_key(item) for item in value)
    return False


def _metadata_audit(root: Path, records: tuple[BenchmarkRunRecord, ...]) -> MetadataAudit:
    metadata_files = sorted((root / "artifacts" / "objects").glob("*/*/metadata.json"))
    references = tuple(
        ArtifactRef.model_validate_json(path.read_text(encoding="utf-8")) for path in metadata_files
    )
    if not references:
        raise ValueError("showcase produced no immutable artifacts")
    reproducibility_complete = all(
        record.problem_hash
        and record.evidence_hash
        and record.policy_hash
        and record.evaluator_version
        and record.problem_plugin_version
        and record.controller_version
        and record.tool_versions
        for record in records
    )
    return MetadataAudit(
        artifact_count=len(references),
        licenses=tuple(sorted({reference.license or "" for reference in references})),
        source_providers=tuple(
            sorted({reference.source_provider or "" for reference in references})
        ),
        all_public=all(
            reference.privacy is PrivacyClassification.PUBLIC for reference in references
        ),
        all_sources_attributed=all(
            bool(reference.source_uri)
            and bool(reference.source_provider)
            and bool(reference.source_version)
            for reference in references
        ),
        all_licenses_declared=all(bool(reference.license) for reference in references),
        no_sensitive_metadata_keys=all(
            not _has_sensitive_key(reference.model_dump(mode="json")) for reference in references
        ),
        reproducibility_complete=bool(reproducibility_complete),
    )


def _instance_reports(
    records: tuple[BenchmarkRunRecord, ...],
) -> tuple[ShowcaseInstanceReport, ...]:
    reports: list[ShowcaseInstanceReport] = []
    for instance_id in sorted({record.instance_id for record in records}):
        candidates = tuple(
            record for record in records if record.instance_id == instance_id and record.feasible
        )
        if not candidates:
            raise ValueError(f"showcase instance {instance_id!r} produced no feasible result")
        selected = max(candidates, key=lambda record: record.comparator_key)
        if (
            selected.problem_hash is None
            or selected.evidence_hash is None
            or selected.policy_hash is None
        ):
            raise ValueError("showcase records lack immutable run identities")
        reports.append(
            ShowcaseInstanceReport(
                id=instance_id,
                problem_type=selected.problem_type,
                comparison=selected.comparison,
                raw_objective=selected.raw_objective,
                overall_metrics=selected.overall_metrics,
                group_metrics=selected.group_metrics,
                scenario_metrics=selected.scenario_metrics,
                baseline_gain=selected.baseline_gain or 0.0,
                comparator_history=tuple(
                    checkpoint.comparator_key for checkpoint in selected.checkpoints
                ),
                problem_hash=selected.problem_hash,
                evidence_hash=selected.evidence_hash,
                policy_hash=selected.policy_hash,
            )
        )
    return tuple(reports)


def _write_report(path: Path, report: ShowcaseReport) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(prefix=".showcase-", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(handle, "w", encoding="utf-8") as stream:
            stream.write(report.model_dump_json(indent=2))
            stream.flush()
            os.fsync(stream.fileno())
        temporary.replace(path)
    finally:
        if temporary.exists():
            temporary.unlink()


async def run_showcase(output_root: str | Path) -> ShowcaseReport:
    """Run or resume the complete offline showcase and publish its release audit."""

    root = _resolve_output_root(output_root)
    manifest = load_showcase_manifest()
    summary = await run_benchmark(manifest, root)
    records = read_run_records(root)
    expected_runs = len(manifest.instances) * len(manifest.comparisons) * len(manifest.run_seeds)
    if len(records) != expected_runs or summary.run_count != expected_runs:
        raise ValueError("showcase did not produce its complete expected run matrix")
    budget = manifest.budgets[0].resources
    report = ShowcaseReport(
        dataset=ShowcaseDataset(),
        default_budget=budget.model_dump(mode="json"),
        benchmark_summary=ShowcaseBenchmarkSummary(
            benchmark_id=summary.benchmark_id,
            manifest_hash=summary.manifest_hash,
            run_count=summary.run_count,
            aggregate_group_count=len(summary.groups),
            paired_delta_count=len(summary.paired_deltas),
        ),
        instances=_instance_reports(records),
        profile=_release_profile(records),
        metadata_audit=_metadata_audit(root, records),
        hardware_validation={
            "cpu_fake": "passed",
            "local_cuda": (
                "passed: RTX 5060 Ti 16 GB, Torch 2.11.0+cu128, CUDA 12.8, "
                "Gemma 4 E2B BF16/SDPA smoke"
            ),
            "remote_worker": "pending: protocol is CPU/fake tested; no rented host was used",
        },
        limitations=(
            "The frozen release dataset is synthetic and demonstrates methods, not a policy "
            "recommendation for a real community.",
            "Monitor placement is deferred until a validated health-impact model is available.",
            "The single RTX 5060 Ti validation is a compatibility smoke, not a universal "
            "performance claim.",
            "Optimality is reported only where complete enumeration produced a verified bound.",
        ),
    )
    _write_report(root / "release-report.json", report)
    return report


__all__ = [
    "MAX_COMPACT_CONTEXT_BYTES",
    "MetadataAudit",
    "ReleaseProfile",
    "ShowcaseBenchmarkSummary",
    "ShowcaseDataset",
    "ShowcaseInstanceReport",
    "ShowcaseReport",
    "ToolLatencyProfile",
    "load_showcase_manifest",
    "run_showcase",
    "showcase_manifest_path",
]
