"""Live/open-data provider contracts, implementations, caching, and HTTP resilience."""

from oasis.providers.adapters import (
    HttpSourceSnapshotProvider,
    NominatimPlaceResolver,
    OsrmRoutingMatrixProvider,
    StacCatalogSearcher,
)
from oasis.providers.cache import LocalSnapshotCache, MemorySnapshotCache
from oasis.providers.http import (
    ApiKeyAuthentication,
    BearerTokenAuthentication,
    HttpPolicy,
    NoAuthentication,
    ResilientHttpClient,
)
from oasis.providers.models import (
    CatalogAsset,
    CatalogItem,
    CatalogSearchRequest,
    CatalogSearchResult,
    FreshnessPolicy,
    PlaceCandidate,
    PlaceResolution,
    PlaceResolveRequest,
    ProviderError,
    ProviderErrorCode,
    ProviderProvenance,
    ProviderRequestContext,
    RetrievedSource,
    RouteAnnotation,
    RouteMatrixRequest,
    RouteMatrixResult,
    SnapshotCacheEntry,
    SourceFormat,
    SourceSnapshotRequest,
)
from oasis.providers.protocols import (
    CatalogSearcher,
    PlaceResolver,
    RoutingMatrixProvider,
    SnapshotCache,
    SourceSnapshotProvider,
)
from oasis.providers.redaction import REDACTED, RedactingLogger, redact_mapping, redact_url

__all__ = [
    "REDACTED",
    "ApiKeyAuthentication",
    "BearerTokenAuthentication",
    "CatalogAsset",
    "CatalogItem",
    "CatalogSearchRequest",
    "CatalogSearchResult",
    "CatalogSearcher",
    "FreshnessPolicy",
    "HttpPolicy",
    "HttpSourceSnapshotProvider",
    "LocalSnapshotCache",
    "MemorySnapshotCache",
    "NoAuthentication",
    "NominatimPlaceResolver",
    "OsrmRoutingMatrixProvider",
    "PlaceCandidate",
    "PlaceResolution",
    "PlaceResolveRequest",
    "PlaceResolver",
    "ProviderError",
    "ProviderErrorCode",
    "ProviderProvenance",
    "ProviderRequestContext",
    "RedactingLogger",
    "ResilientHttpClient",
    "RetrievedSource",
    "RouteAnnotation",
    "RouteMatrixRequest",
    "RouteMatrixResult",
    "RoutingMatrixProvider",
    "SnapshotCache",
    "SnapshotCacheEntry",
    "SourceFormat",
    "SourceSnapshotProvider",
    "SourceSnapshotRequest",
    "StacCatalogSearcher",
    "redact_mapping",
    "redact_url",
]
