"""Public optimization problem schemas, plugins, registry, and search contracts."""

from oasis.problems.location_allocation import (
    LocationAllocationPlugin,
    ProblemDataError,
    create_problem_registry,
    load_problem_data,
    plan_hash,
    problem_hashes,
)
from oasis.problems.protocols import Deadline, ProblemPlugin
from oasis.problems.registry import (
    ProblemRegistry,
    ProblemRegistryError,
    create_builtin_problem_registry,
)
from oasis.problems.routing import (
    RouteDataError,
    RouteServiceData,
    RouteServicePlugin,
    load_route_data,
    route_plan_hash,
    route_problem_hashes,
)
from oasis.problems.schemas import (
    Comparison,
    EquityGroup,
    EquityObjective,
    LocationAllocationPolicy,
    LocationAllocationProblem,
    LocationProblemType,
    ResultView,
    RouteProblemType,
    RouteScenario,
    RouteServicePolicy,
    RouteServiceProblem,
    ScenarioAggregation,
    Scorecard,
    SearchResumeToken,
    SearchStrategy,
    ServiceScenario,
    ValidationIssue,
    ValidationReport,
    VerifiedBound,
)

__all__ = [
    "Comparison",
    "Deadline",
    "EquityGroup",
    "EquityObjective",
    "LocationAllocationPlugin",
    "LocationAllocationPolicy",
    "LocationAllocationProblem",
    "LocationProblemType",
    "ProblemDataError",
    "ProblemPlugin",
    "ProblemRegistry",
    "ProblemRegistryError",
    "ResultView",
    "RouteDataError",
    "RouteProblemType",
    "RouteScenario",
    "RouteServiceData",
    "RouteServicePlugin",
    "RouteServicePolicy",
    "RouteServiceProblem",
    "ScenarioAggregation",
    "Scorecard",
    "SearchResumeToken",
    "SearchStrategy",
    "ServiceScenario",
    "ValidationIssue",
    "ValidationReport",
    "VerifiedBound",
    "create_builtin_problem_registry",
    "create_problem_registry",
    "load_problem_data",
    "load_route_data",
    "plan_hash",
    "problem_hashes",
    "route_plan_hash",
    "route_problem_hashes",
]
